version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "8080:80"

  # database:
  #   image: postgres
  #   environment:
  #     - POSTGRES_USER=your_db_user
  #     - POSTGRES_PASSWORD=your_db_password
  #     - POSTGRES_DB=your_db_name
